on: [push]

jobs:
  build_native:
    runs-on: ubuntu-latest
    name: Build native Quarkus app
    steps:
      - name: Checkout the code
        uses: actions/checkout@master
      - name: Build native executable and upload it as an artifact
        run: |
          docker build . --file Dockerfile -t binary-image
          id=$(docker create binary-image)
          version=$(grep --max-count=1 '<version>' pom.xml | awk -F '>' '{ print $2 }' | awk -F '<' '{ print $1 }')
          artifactId=$(grep --max-count=1 '<artifactId>' pom.xml | awk -F '>' '{ print $2 }' | awk -F '<' '{ print $1 }')
          docker cp $id:/usr/src/app/target/${artifactId}-${version}-runner application-runner
      - name: Upload binary app
        uses: actions/upload-artifact@v1
        with:
          name: application-runner
          path: application-runner