on: [push]

jobs:
  native_build:
    runs-on: ubuntu-latest
    name: Build native Quarkus app
    steps:
      - name: Checkout the code
        uses: actions/checkout@master
      - name: Build native executable and upload it as an artifact
        run: |
          docker build . --file docker/native_build/Dockerfile -t native-build-image
          id=$(docker create native-build-image)
          docker cp $id:/usr/src/app/target/app-runner app-runner
      - name: Upload native executable
        uses: actions/upload-artifact@v1
        with:
          name: native-executable
          path: app-runner

  dockerize:
    runs-on: ubuntu-latest
    name: Embed the native executable in a Docker container
    needs: native_build
    steps:
      - name: Checkout the code
        uses: actions/checkout@master
      - name: Download the binary
        uses: actions/download-artifact@v1
        with:
          name: native-executable
      - name: Dockerize
        run: |
          chmod u+x native-executable/app-runner
          docker build . --file docker/dockerize/Dockerfile -t maxday/url-shortener
      - name: Login to DockerHub registry
        run: |
          echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Push docker image
        run: |
          docker push maxday/url-shortener
