on: [push]

jobs:
  native_build:
    runs-on: ubuntu-latest
    name: Build native Quarkus app
    steps:
      - name: Checkout the code
        uses: actions/checkout@master
      - name: Build native executable and upload it as an artifact
        run: echo coucou >> xxx-app-runner
        #uses: maxday/quarkus-native-build-docker-action@1
        #with:
          #outputName: xxx-app-runner
      - name: Upload native executable
        uses: actions/upload-artifact@v1
        with:
          name: native-executable
          path: xxx-app-runner

  dockerize:
    runs-on: ubuntu-latest
    name: Embed the native executable in a Docker container
    needs: native_build
    steps:
      - name: Checkout the code
        uses: actions/checkout@master
      - name: Download the binary
        uses: actions/download-artifact@v1
        with:
          name: native-executable
      - name: Dockerize
        id: dockerize
        uses: maxday/quarkus-dockerize-action@master
        with:
          tag: gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_APP_NAME }}
          executablePath: native-executable/xxx-app-runner
      - name: Login to GCP
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_email: ${{ secrets.GCP_EMAIL }}
          service_account_key: ${{ secrets.GCP_ACCOUNT_KEY }}
          project_id: ${{ secrets.GCP_PROJECT }}
          export_default_credentials: true
      - name: Configure Docker to use GCP
        run: "gcloud auth configure-docker --quiet"
      - name: Push image to GCP
        run: docker push gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_APP_NAME }}
      - name: Deploy 
        run: |
          gcloud components install beta --quiet  &&  \
          gcloud auth configure-docker --quiet &&  \
          gcloud beta run deploy ${{ secrets.GCP_SERVICE_NAME }} \
          --image gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_APP_NAME }} \
          --platform ${{ secrets.GCP_PLATFORM }} \
          --allow-unauthenticated --service-account ${{ secrets.GCP_ACCOUNT_KEY }} \
          --region ${{ secrets.GCP_REGION }} \
          --set-env-vars DISABLE_SIGNAL_HANDLERS=1
          
      